import type { Template } from './types'

export const mockTemplates: Template[] = [
  {
    id: '1',
    name: 'FYB Face of the Day - Classic',
    category: 'fyb',
    usageCount: 245,
    previewImage: '/api/placeholder/800/600',
    status: 'public',
    fields: [
      {
        id: 'f1',
        name: 'studentName',
        type: 'text',
        label: 'Student Name',
        placeholder: 'Enter your full name',
        required: true,
        position: { x: 400, y: 200 },
        style: {
          fontSize: 48,
          fontFamily: 'Arial',
          color: '#1a1a1a',
          fontWeight: 'bold',
          textAlign: 'center',
          maxWidth: 700,
        },
      },
      {
        id: 'f2',
        name: 'department',
        type: 'text',
        label: 'Department',
        placeholder: 'e.g., Computer Science',
        required: true,
        position: { x: 400, y: 280 },
        style: {
          fontSize: 32,
          fontFamily: 'Arial',
          color: '#4a5568',
          fontWeight: 'normal',
          textAlign: 'center',
          maxWidth: 700,
        },
      },
      {
        id: 'f3',
        name: 'photo',
        type: 'image',
        label: 'Student Photo',
        placeholder: 'Upload your photo',
        required: true,
        position: { x: 400, y: 100 },
        style: {
          maxWidth: 180,
          maxHeight: 180,
        },
      },
      {
        id: 'f4',
        name: 'date',
        type: 'date',
        label: 'Date',
        placeholder: 'Select date',
        required: true,
        position: { x: 400, y: 350 },
        style: {
          fontSize: 24,
          fontFamily: 'Arial',
          color: '#718096',
          fontWeight: 'normal',
          textAlign: 'center',
          maxWidth: 600,
        },
      },
    ],
    canvasConfig: {
      width: 800,
      height: 600,
      backgroundColor: '#ffffff',
    },
  },
  {
    id: '2',
    name: 'FYB Face of the Week - Modern',
    category: 'fyb',
    usageCount: 189,
    previewImage: '/api/placeholder/800/600',
    status: 'public',
    fields: [
      {
        id: 'f1',
        name: 'studentName',
        type: 'text',
        label: 'Student Name',
        placeholder: 'Enter your full name',
        required: true,
        position: { x: 400, y: 250 },
        style: {
          fontSize: 56,
          fontFamily: 'Georgia',
          color: '#2d3748',
          fontWeight: 'bold',
          textAlign: 'center',
          maxWidth: 700,
        },
      },
      {
        id: 'f2',
        name: 'department',
        type: 'text',
        label: 'Department',
        placeholder: 'e.g., Electrical Engineering',
        required: true,
        position: { x: 400, y: 320 },
        style: {
          fontSize: 28,
          fontFamily: 'Georgia',
          color: '#4a5568',
          fontWeight: 'normal',
          textAlign: 'center',
          maxWidth: 700,
        },
      },
      {
        id: 'f3',
        name: 'photo',
        type: 'image',
        label: 'Student Photo',
        placeholder: 'Upload your photo',
        required: true,
        position: { x: 400, y: 120 },
        style: {
          maxWidth: 180,
          maxHeight: 180,
        },
      },
      {
        id: 'f4',
        name: 'week',
        type: 'text',
        label: 'Week',
        placeholder: 'e.g., Week 1',
        required: true,
        position: { x: 400, y: 380 },
        style: {
          fontSize: 20,
          fontFamily: 'Arial',
          color: '#718096',
          fontWeight: 'normal',
          textAlign: 'center',
          maxWidth: 600,
        },
      },
    ],
    canvasConfig: {
      width: 800,
      height: 600,
      backgroundColor: '#f7fafc',
    },
  },
  {
    id: '3',
    name: 'Sign-out Flyer - Elegant',
    category: 'signout',
    department: 'Computer Science',
    departmentLockCode: 'CS2024',
    usageCount: 156,
    previewImage: '/api/placeholder/800/600',
    status: 'locked',
    fields: [
      {
        id: 'f1',
        name: 'studentName',
        type: 'text',
        label: 'Student Name',
        placeholder: 'Enter your full name',
        required: true,
        position: { x: 400, y: 180 },
        style: {
          fontSize: 52,
          fontFamily: 'Times New Roman',
          color: '#1a202c',
          fontWeight: 'bold',
          textAlign: 'center',
          maxWidth: 700,
        },
      },
      {
        id: 'f2',
        name: 'department',
        type: 'text',
        label: 'Department',
        placeholder: 'e.g., Computer Science',
        required: true,
        position: { x: 400, y: 260 },
        style: {
          fontSize: 36,
          fontFamily: 'Times New Roman',
          color: '#2d3748',
          fontWeight: 'normal',
          textAlign: 'center',
          maxWidth: 700,
        },
      },
      {
        id: 'f3',
        name: 'photo',
        type: 'image',
        label: 'Student Photo',
        placeholder: 'Upload your photo',
        required: true,
        position: { x: 400, y: 100 },
        style: {
          maxWidth: 160,
          maxHeight: 160,
        },
      },
      {
        id: 'f4',
        name: 'writeUp',
        type: 'text',
        label: 'Write-up',
        placeholder: 'Enter your write-up',
        required: true,
        position: { x: 400, y: 340 },
        style: {
          fontSize: 18,
          fontFamily: 'Arial',
          color: '#4a5568',
          fontWeight: 'normal',
          textAlign: 'center',
          maxWidth: 680,
        },
      },
      {
        id: 'f5',
        name: 'date',
        type: 'date',
        label: 'Sign-out Date',
        placeholder: 'Select date',
        required: true,
        position: { x: 400, y: 420 },
        style: {
          fontSize: 22,
          fontFamily: 'Arial',
          color: '#718096',
          fontWeight: 'normal',
          textAlign: 'center',
          maxWidth: 600,
        },
      },
    ],
    canvasConfig: {
      width: 800,
      height: 600,
      backgroundColor: '#ffffff',
    },
  },
  {
    id: '4',
    name: 'Sign-out Flyer - Vibrant',
    category: 'signout',
    usageCount: 203,
    previewImage: '/api/placeholder/800/600',
    status: 'public',
    fields: [
      {
        id: 'f1',
        name: 'studentName',
        type: 'text',
        label: 'Student Name',
        placeholder: 'Enter your full name',
        required: true,
        position: { x: 400, y: 200 },
        style: {
          fontSize: 50,
          fontFamily: 'Arial',
          color: '#ffffff',
          fontWeight: 'bold',
          textAlign: 'center',
        },
      },
      {
        id: 'f2',
        name: 'department',
        type: 'text',
        label: 'Department',
        placeholder: 'e.g., Mechanical Engineering',
        required: true,
        position: { x: 400, y: 280 },
        style: {
          fontSize: 32,
          fontFamily: 'Arial',
          color: '#e2e8f0',
          fontWeight: 'normal',
          textAlign: 'center',
        },
      },
      {
        id: 'f3',
        name: 'photo',
        type: 'image',
        label: 'Student Photo',
        placeholder: 'Upload your photo',
        required: true,
        position: { x: 400, y: 100 },
        style: {},
      },
      {
        id: 'f4',
        name: 'writeUp',
        type: 'text',
        label: 'Write-up',
        placeholder: 'Enter your write-up',
        required: true,
        position: { x: 400, y: 360 },
        style: {
          fontSize: 16,
          fontFamily: 'Arial',
          color: '#cbd5e0',
          fontWeight: 'normal',
          textAlign: 'center',
        },
      },
    ],
    canvasConfig: {
      width: 800,
      height: 600,
      backgroundColor: '#0ea5e9',
    },
  },
  {
    id: '5',
    name: 'FYB Face of the Day - Minimalist',
    category: 'fyb',
    department: 'Electrical Engineering',
    departmentLockCode: 'EE2024',
    usageCount: 98,
    previewImage: '/api/placeholder/800/600',
    status: 'locked',
    fields: [
      {
        id: 'f1',
        name: 'studentName',
        type: 'text',
        label: 'Student Name',
        placeholder: 'Enter your full name',
        required: true,
        position: { x: 400, y: 220 },
        style: {
          fontSize: 44,
          fontFamily: 'Helvetica',
          color: '#1a1a1a',
          fontWeight: 'bold',
          textAlign: 'center',
        },
      },
      {
        id: 'f2',
        name: 'department',
        type: 'text',
        label: 'Department',
        placeholder: 'e.g., Electrical Engineering',
        required: true,
        position: { x: 400, y: 300 },
        style: {
          fontSize: 28,
          fontFamily: 'Helvetica',
          color: '#4a5568',
          fontWeight: 'normal',
          textAlign: 'center',
        },
      },
      {
        id: 'f3',
        name: 'photo',
        type: 'image',
        label: 'Student Photo',
        placeholder: 'Upload your photo',
        required: true,
        position: { x: 400, y: 100 },
        style: {},
      },
    ],
    canvasConfig: {
      width: 800,
      height: 600,
      backgroundColor: '#ffffff',
    },
  },
  {
    id: '6',
    name: 'Face of the Finalist - Classic Profile',
    category: 'fyb',
    usageCount: 0,
    previewImage: '/api/placeholder/1200/1600',
    status: 'public',
    fields: [
      // Photo
      {
        id: 'f1',
        name: 'photo',
        type: 'image',
        label: 'Profile Photo',
        placeholder: 'Upload your photo',
        required: true,
        section: 'Profile Photo',
        position: { x: 350, y: 650 },
        style: {},
      },
      // Personal details
      {
        id: 'f2',
        name: 'firstName',
        type: 'text',
        label: 'First Name',
        placeholder: 'e.g. Daniel',
        required: true,
        section: 'Personal Details',
        position: { x: 350, y: 1030 },
        style: {
          fontSize: 80,
          fontFamily: 'Arial',
          color: '#ffffff',
          fontWeight: 'bold',
          textAlign: 'left',
        },
      },
      {
        id: 'f3',
        name: 'otherNames',
        type: 'text',
        label: 'Other Names',
        placeholder: 'e.g. Gara Monday',
        required: true,
        section: 'Personal Details',
        position: { x: 350, y: 1110 },
        style: {
          fontSize: 28,
          fontFamily: 'Arial',
          color: '#ffffff',
          fontWeight: 'normal',
          textAlign: 'left',
        },
      },
      {
        id: 'f4',
        name: 'nickname',
        type: 'text',
        label: 'Nickname',
        placeholder: 'e.g. Nezzy (Senator Nezzy)',
        required: false,
        section: 'Personal Details',
        position: { x: 350, y: 1190 },
        style: {
          fontSize: 20,
          fontFamily: 'Arial',
          color: '#ffffff',
          fontWeight: 'normal',
          textAlign: 'left',
        },
      },
      {
        id: 'f5',
        name: 'dob',
        type: 'text',
        label: 'Date of Birth',
        placeholder: 'e.g. 05th of May',
        required: false,
        section: 'Personal Details',
        position: { x: 350, y: 1230 },
        style: {
          fontSize: 18,
          fontFamily: 'Arial',
          color: '#ffffff',
          fontWeight: 'normal',
          textAlign: 'left',
        },
      },
      {
        id: 'f6',
        name: 'stateOfOrigin',
        type: 'text',
        label: 'State of Origin',
        placeholder: 'e.g. Plateau State',
        required: false,
        section: 'Personal Details',
        position: { x: 350, y: 1270 },
        style: {
          fontSize: 18,
          fontFamily: 'Arial',
          color: '#ffffff',
          fontWeight: 'normal',
          textAlign: 'left',
        },
      },
      // Header / school info
      {
        id: 'f7',
        name: 'universityName',
        type: 'text',
        label: 'University Name',
        placeholder: 'e.g. University of Jos',
        required: true,
        section: 'School Info',
        position: { x: 830, y: 190 },
        style: {
          fontSize: 26,
          fontFamily: 'Arial',
          color: '#111827',
          fontWeight: 'bold',
          textAlign: 'left',
        },
      },
      {
        id: 'f8',
        name: 'departmentName',
        type: 'text',
        label: 'Department',
        placeholder: 'e.g. Dept. of Actuarial Science',
        required: true,
        section: 'School Info',
        position: { x: 830, y: 225 },
        style: {
          fontSize: 20,
          fontFamily: 'Arial',
          color: '#111827',
          fontWeight: 'normal',
          textAlign: 'left',
        },
      },
      {
        id: 'f9',
        name: 'fybYear',
        type: 'text',
        label: 'FYB Year Text',
        placeholder: 'e.g. FYB 2025',
        required: true,
        section: 'School Info',
        position: { x: 830, y: 320 },
        style: {
          fontSize: 40,
          fontFamily: 'Arial',
          color: '#111827',
          fontWeight: 'bold',
          textAlign: 'left',
        },
      },
      // Profile block
      {
        id: 'f10',
        name: 'hobbies',
        type: 'text',
        label: 'Hobbies',
        placeholder: 'e.g. Music, Politics, Shoe making',
        required: false,
        section: 'Profile',
        position: { x: 870, y: 430 },
        style: {
          fontSize: 16,
          fontFamily: 'Arial',
          color: '#111827',
          fontWeight: 'normal',
          textAlign: 'left',
        },
      },
      {
        id: 'f11',
        name: 'relationshipStatus',
        type: 'text',
        label: 'Relationship Status',
        placeholder: 'e.g. Single',
        required: false,
        section: 'Profile',
        position: { x: 870, y: 460 },
        style: {
          fontSize: 16,
          fontFamily: 'Arial',
          color: '#111827',
          fontWeight: 'normal',
          textAlign: 'left',
        },
      },
      {
        id: 'f12',
        name: 'bestCourse',
        type: 'text',
        label: 'Best Course',
        placeholder: 'e.g. Theory of Interest',
        required: false,
        section: 'Profile',
        position: { x: 870, y: 490 },
        style: {
          fontSize: 16,
          fontFamily: 'Arial',
          color: '#111827',
          fontWeight: 'normal',
          textAlign: 'left',
        },
      },
      {
        id: 'f13',
        name: 'bestLevel',
        type: 'text',
        label: 'Best Level',
        placeholder: 'e.g. 300 Level',
        required: false,
        section: 'Profile',
        position: { x: 870, y: 520 },
        style: {
          fontSize: 16,
          fontFamily: 'Arial',
          color: '#111827',
          fontWeight: 'normal',
          textAlign: 'left',
        },
      },
      {
        id: 'f14',
        name: 'classCartel',
        type: 'text',
        label: 'Class Cartel (Squad)',
        placeholder: 'e.g. Flow, Myles, Zendi, Owen, Tari',
        required: false,
        section: 'Profile',
        position: { x: 870, y: 550 },
        style: {
          fontSize: 16,
          fontFamily: 'Arial',
          color: '#111827',
          fontWeight: 'normal',
          textAlign: 'left',
        },
      },
      {
        id: 'f15',
        name: 'alternativeCourse',
        type: 'text',
        label: 'If not this course, what else?',
        placeholder: 'e.g. Criminology',
        required: false,
        section: 'Profile',
        position: { x: 870, y: 580 },
        style: {
          fontSize: 16,
          fontFamily: 'Arial',
          color: '#111827',
          fontWeight: 'normal',
          textAlign: 'left',
        },
      },
      {
        id: 'f16',
        name: 'sideHustle',
        type: 'text',
        label: 'Side Hustle',
        placeholder: 'e.g. Shoe Making',
        required: false,
        section: 'Profile',
        position: { x: 870, y: 610 },
        style: {
          fontSize: 16,
          fontFamily: 'Arial',
          color: '#111827',
          fontWeight: 'normal',
          textAlign: 'left',
        },
      },
      {
        id: 'f17',
        name: 'favouriteQuote',
        type: 'text',
        label: 'Favourite Quote',
        placeholder: 'e.g. Everybody get him time to make am for life',
        required: false,
        section: 'Profile',
        position: { x: 900, y: 660 },
        style: {
          fontSize: 16,
          fontFamily: 'Arial',
          color: '#111827',
          fontWeight: 'normal',
          textAlign: 'left',
        },
      },
      {
        id: 'f18',
        name: 'partingWords',
        type: 'text',
        label: 'Parting Words',
        placeholder: 'e.g. Help one another because you never can tell.',
        required: false,
        section: 'Profile',
        position: { x: 900, y: 700 },
        style: {
          fontSize: 16,
          fontFamily: 'Arial',
          color: '#111827',
          fontWeight: 'normal',
          textAlign: 'left',
        },
      },
      // Socials / contact
      {
        id: 'f19',
        name: 'phonePrimary',
        type: 'text',
        label: 'Phone (Primary)',
        placeholder: 'e.g. +234 810 257 xxxx',
        required: false,
        section: 'Contact & Socials',
        position: { x: 900, y: 880 },
        style: {
          fontSize: 16,
          fontFamily: 'Arial',
          color: '#ffffff',
          fontWeight: 'normal',
          textAlign: 'left',
        },
      },
      {
        id: 'f20',
        name: 'phoneSecondary',
        type: 'text',
        label: 'Phone (Secondary)',
        placeholder: 'Optional phone',
        required: false,
        section: 'Contact & Socials',
        position: { x: 900, y: 910 },
        style: {
          fontSize: 16,
          fontFamily: 'Arial',
          color: '#ffffff',
          fontWeight: 'normal',
          textAlign: 'left',
        },
      },
      {
        id: 'f21',
        name: 'contactEmail',
        type: 'text',
        label: 'Contact Email',
        placeholder: 'e.g. yourname@gmail.com',
        required: false,
        section: 'Contact & Socials',
        position: { x: 900, y: 940 },
        style: {
          fontSize: 16,
          fontFamily: 'Arial',
          color: '#ffffff',
          fontWeight: 'normal',
          textAlign: 'left',
        },
      },
      {
        id: 'f22',
        name: 'instagram',
        type: 'text',
        label: 'Instagram Handle',
        placeholder: '@yourhandle',
        required: false,
        section: 'Contact & Socials',
        position: { x: 900, y: 970 },
        style: {
          fontSize: 16,
          fontFamily: 'Arial',
          color: '#ffffff',
          fontWeight: 'normal',
          textAlign: 'left',
        },
      },
      {
        id: 'f23',
        name: 'xHandle',
        type: 'text',
        label: 'X / Twitter Handle',
        placeholder: '@yourhandle',
        required: false,
        section: 'Contact & Socials',
        position: { x: 900, y: 1000 },
        style: {
          fontSize: 16,
          fontFamily: 'Arial',
          color: '#ffffff',
          fontWeight: 'normal',
          textAlign: 'left',
        },
      },
      {
        id: 'f24',
        name: 'facebook',
        type: 'text',
        label: 'Facebook Name',
        placeholder: 'Your Facebook name',
        required: false,
        section: 'Contact & Socials',
        position: { x: 900, y: 1030 },
        style: {
          fontSize: 16,
          fontFamily: 'Arial',
          color: '#ffffff',
          fontWeight: 'normal',
          textAlign: 'left',
        },
      },
      // Logos
      {
        id: 'f25',
        name: 'logoPrimary',
        type: 'image',
        label: 'Primary School Logo',
        placeholder: 'Upload primary logo',
        required: false,
        section: 'Logos',
        position: { x: 760, y: 130 },
        style: {},
      },
      {
        id: 'f26',
        name: 'logoSecondary',
        type: 'image',
        label: 'Secondary Logo (optional)',
        placeholder: 'Upload secondary logo',
        required: false,
        section: 'Logos',
        position: { x: 900, y: 130 },
        style: {},
      },
    ],
    canvasConfig: {
      width: 1200,
      height: 1600,
      backgroundColor: '#e0f2ff',
    },
  },
]

// Initialize department codes in localStorage if not exists
if (typeof window !== 'undefined') {
  const existingCodes = localStorage.getItem('department_codes')
  if (!existingCodes) {
    const codes = [
      {
        code: 'CS2024',
        department: 'Computer Science',
        expiresAt: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString(),
        usageLimit: 1000,
        usedCount: 0,
      },
      {
        code: 'EE2024',
        department: 'Electrical Engineering',
        expiresAt: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString(),
        usageLimit: 1000,
        usedCount: 0,
      },
    ]
    localStorage.setItem('department_codes', JSON.stringify(codes))
  }
}

