import type { Template } from './types'

export const mockTemplates: Template[] = [
  {
    id: '1',
    name: 'FYB Face of the Day - Classic',
    category: 'fyb',
    usageCount: 245,
    previewImage: '/api/placeholder/800/600',
    status: 'public',
    fields: [
      {
        id: 'f1',
        name: 'studentName',
        type: 'text',
        label: 'Student Name',
        placeholder: 'Enter your full name',
        required: true,
        position: { x: 400, y: 200 },
        style: {
          fontSize: 48,
          fontFamily: 'Arial',
          color: '#1a1a1a',
          fontWeight: 'bold',
          textAlign: 'center',
        },
      },
      {
        id: 'f2',
        name: 'department',
        type: 'text',
        label: 'Department',
        placeholder: 'e.g., Computer Science',
        required: true,
        position: { x: 400, y: 280 },
        style: {
          fontSize: 32,
          fontFamily: 'Arial',
          color: '#4a5568',
          fontWeight: 'normal',
          textAlign: 'center',
        },
      },
      {
        id: 'f3',
        name: 'photo',
        type: 'image',
        label: 'Student Photo',
        placeholder: 'Upload your photo',
        required: true,
        position: { x: 400, y: 100 },
        style: {},
      },
      {
        id: 'f4',
        name: 'date',
        type: 'date',
        label: 'Date',
        placeholder: 'Select date',
        required: true,
        position: { x: 400, y: 350 },
        style: {
          fontSize: 24,
          fontFamily: 'Arial',
          color: '#718096',
          fontWeight: 'normal',
          textAlign: 'center',
        },
      },
    ],
    canvasConfig: {
      width: 800,
      height: 600,
      backgroundColor: '#ffffff',
    },
  },
  {
    id: '2',
    name: 'FYB Face of the Week - Modern',
    category: 'fyb',
    usageCount: 189,
    previewImage: '/api/placeholder/800/600',
    status: 'public',
    fields: [
      {
        id: 'f1',
        name: 'studentName',
        type: 'text',
        label: 'Student Name',
        placeholder: 'Enter your full name',
        required: true,
        position: { x: 400, y: 250 },
        style: {
          fontSize: 56,
          fontFamily: 'Georgia',
          color: '#2d3748',
          fontWeight: 'bold',
          textAlign: 'center',
        },
      },
      {
        id: 'f2',
        name: 'department',
        type: 'text',
        label: 'Department',
        placeholder: 'e.g., Electrical Engineering',
        required: true,
        position: { x: 400, y: 320 },
        style: {
          fontSize: 28,
          fontFamily: 'Georgia',
          color: '#4a5568',
          fontWeight: 'normal',
          textAlign: 'center',
        },
      },
      {
        id: 'f3',
        name: 'photo',
        type: 'image',
        label: 'Student Photo',
        placeholder: 'Upload your photo',
        required: true,
        position: { x: 400, y: 120 },
        style: {},
      },
      {
        id: 'f4',
        name: 'week',
        type: 'text',
        label: 'Week',
        placeholder: 'e.g., Week 1',
        required: true,
        position: { x: 400, y: 380 },
        style: {
          fontSize: 20,
          fontFamily: 'Arial',
          color: '#718096',
          fontWeight: 'normal',
          textAlign: 'center',
        },
      },
    ],
    canvasConfig: {
      width: 800,
      height: 600,
      backgroundColor: '#f7fafc',
    },
  },
  {
    id: '3',
    name: 'Sign-out Flyer - Elegant',
    category: 'signout',
    department: 'Computer Science',
    departmentLockCode: 'CS2024',
    usageCount: 156,
    previewImage: '/api/placeholder/800/600',
    status: 'locked',
    fields: [
      {
        id: 'f1',
        name: 'studentName',
        type: 'text',
        label: 'Student Name',
        placeholder: 'Enter your full name',
        required: true,
        position: { x: 400, y: 180 },
        style: {
          fontSize: 52,
          fontFamily: 'Times New Roman',
          color: '#1a202c',
          fontWeight: 'bold',
          textAlign: 'center',
        },
      },
      {
        id: 'f2',
        name: 'department',
        type: 'text',
        label: 'Department',
        placeholder: 'e.g., Computer Science',
        required: true,
        position: { x: 400, y: 260 },
        style: {
          fontSize: 36,
          fontFamily: 'Times New Roman',
          color: '#2d3748',
          fontWeight: 'normal',
          textAlign: 'center',
        },
      },
      {
        id: 'f3',
        name: 'photo',
        type: 'image',
        label: 'Student Photo',
        placeholder: 'Upload your photo',
        required: true,
        position: { x: 400, y: 100 },
        style: {},
      },
      {
        id: 'f4',
        name: 'writeUp',
        type: 'text',
        label: 'Write-up',
        placeholder: 'Enter your write-up',
        required: true,
        position: { x: 400, y: 340 },
        style: {
          fontSize: 18,
          fontFamily: 'Arial',
          color: '#4a5568',
          fontWeight: 'normal',
          textAlign: 'center',
        },
      },
      {
        id: 'f5',
        name: 'date',
        type: 'date',
        label: 'Sign-out Date',
        placeholder: 'Select date',
        required: true,
        position: { x: 400, y: 420 },
        style: {
          fontSize: 22,
          fontFamily: 'Arial',
          color: '#718096',
          fontWeight: 'normal',
          textAlign: 'center',
        },
      },
    ],
    canvasConfig: {
      width: 800,
      height: 600,
      backgroundColor: '#ffffff',
    },
  },
  {
    id: '4',
    name: 'Sign-out Flyer - Vibrant',
    category: 'signout',
    usageCount: 203,
    previewImage: '/api/placeholder/800/600',
    status: 'public',
    fields: [
      {
        id: 'f1',
        name: 'studentName',
        type: 'text',
        label: 'Student Name',
        placeholder: 'Enter your full name',
        required: true,
        position: { x: 400, y: 200 },
        style: {
          fontSize: 50,
          fontFamily: 'Arial',
          color: '#ffffff',
          fontWeight: 'bold',
          textAlign: 'center',
        },
      },
      {
        id: 'f2',
        name: 'department',
        type: 'text',
        label: 'Department',
        placeholder: 'e.g., Mechanical Engineering',
        required: true,
        position: { x: 400, y: 280 },
        style: {
          fontSize: 32,
          fontFamily: 'Arial',
          color: '#e2e8f0',
          fontWeight: 'normal',
          textAlign: 'center',
        },
      },
      {
        id: 'f3',
        name: 'photo',
        type: 'image',
        label: 'Student Photo',
        placeholder: 'Upload your photo',
        required: true,
        position: { x: 400, y: 100 },
        style: {},
      },
      {
        id: 'f4',
        name: 'writeUp',
        type: 'text',
        label: 'Write-up',
        placeholder: 'Enter your write-up',
        required: true,
        position: { x: 400, y: 360 },
        style: {
          fontSize: 16,
          fontFamily: 'Arial',
          color: '#cbd5e0',
          fontWeight: 'normal',
          textAlign: 'center',
        },
      },
    ],
    canvasConfig: {
      width: 800,
      height: 600,
      backgroundColor: '#0ea5e9',
    },
  },
  {
    id: '5',
    name: 'FYB Face of the Day - Minimalist',
    category: 'fyb',
    department: 'Electrical Engineering',
    departmentLockCode: 'EE2024',
    usageCount: 98,
    previewImage: '/api/placeholder/800/600',
    status: 'locked',
    fields: [
      {
        id: 'f1',
        name: 'studentName',
        type: 'text',
        label: 'Student Name',
        placeholder: 'Enter your full name',
        required: true,
        position: { x: 400, y: 220 },
        style: {
          fontSize: 44,
          fontFamily: 'Helvetica',
          color: '#1a1a1a',
          fontWeight: 'bold',
          textAlign: 'center',
        },
      },
      {
        id: 'f2',
        name: 'department',
        type: 'text',
        label: 'Department',
        placeholder: 'e.g., Electrical Engineering',
        required: true,
        position: { x: 400, y: 300 },
        style: {
          fontSize: 28,
          fontFamily: 'Helvetica',
          color: '#4a5568',
          fontWeight: 'normal',
          textAlign: 'center',
        },
      },
      {
        id: 'f3',
        name: 'photo',
        type: 'image',
        label: 'Student Photo',
        placeholder: 'Upload your photo',
        required: true,
        position: { x: 400, y: 100 },
        style: {},
      },
    ],
    canvasConfig: {
      width: 800,
      height: 600,
      backgroundColor: '#ffffff',
    },
  },
]

// Initialize department codes in localStorage if not exists
if (typeof window !== 'undefined') {
  const existingCodes = localStorage.getItem('department_codes')
  if (!existingCodes) {
    const codes = [
      {
        code: 'CS2024',
        department: 'Computer Science',
        expiresAt: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString(),
        usageLimit: 1000,
        usedCount: 0,
      },
      {
        code: 'EE2024',
        department: 'Electrical Engineering',
        expiresAt: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString(),
        usageLimit: 1000,
        usedCount: 0,
      },
    ]
    localStorage.setItem('department_codes', JSON.stringify(codes))
  }
}

